import type { CampaignServerBundle, CombatProfile } from '../../engine/server/campaign.js';
import { d8AdjacentWalkableCells, d8NearestWalkableCell, oneShotCampaignDefinition } from './public/pack.js';

const d8ActorCell = (sceneId: string, actorId: string) => oneShotCampaignDefinition.scenes.find(scene => scene.id === sceneId)?.stageActors?.find(actor => actor.id === actorId)?.cell;
const mirrorCell = oneShotCampaignDefinition.scenes.find(scene => scene.id === 'mirror')?.props.find(prop => prop.id === 'true-love-mirror')?.cell
  ?? d8NearestWalkableCell('mirror', -9.2, -2.5);
const mirrorNearbyCells = d8AdjacentWalkableCells('mirror', mirrorCell, 4);
const templeAnterosCell = d8ActorCell('temple', 'anteros-temple') ?? d8NearestWalkableCell('temple', 0, 0);
const dinnerAnterosCell = d8ActorCell('dinner', 'anteros-dinner') ?? d8NearestWalkableCell('dinner', 0, 0);

const villagerProfile = (identityId: string): CombatProfile => ({
  maxHp: 4, armorClass: 10, speedMeters: 9, initiativeBonus: 0, identityId, startsInCombat: false,
  traits: ['Matón de taberna: puede realizar otro golpe sin armas como acción adicional.'],
  attacks: [
    { id: 'villager-unarmed', label: 'Golpe sin armas · +3 · 1d4+1 contundente · 1,5 m', attackBonus: 3, damageDice: '1d4', damageBonus: 1, damageType: 'contundente', range: { kind: 'melee', normalMeters: 1.5 }, animationType: 'melee' },
    { id: 'villager-unarmed-bonus', label: 'Golpe sin armas · acción adicional · +3 · 1d4+1 contundente · 1,5 m', attackBonus: 3, damageDice: '1d4', damageBonus: 1, damageType: 'contundente', range: { kind: 'melee', normalMeters: 1.5 }, actionCost: 'bonus', animationType: 'melee' }
  ]
});

// Story branches, mission items and combat balance are not encoded yet. This
// is an independent private-table campaign, never a Stormwreck save migration.
export const oneShotBundle: CampaignServerBundle = {
  public: oneShotCampaignDefinition, campaignStateVersion: 1,
  characters: {
    maria: { maxHp: 9, inventory: ['Armadura de cuero', 'Arco corto', '20 flechas', '2 dagas', 'Herramientas de ladrón', 'Mochila', 'Bola con 1000 bolas de metal', '2 palanquetas', '2 frascos de aceite'], sheet: { level: 1, armorClass: 14, speedMeters: 7.5, strengthScore: 8, background: 'Criminal', features: ['Mediana piesligeros', 'Ataque furtivo 1d6', 'Afortunada', 'Valiente', 'Agilidad de Mediano', 'Sigiloso por naturaleza'], attacks: ['Daga · +5 · 1d4+3 perforante · alcance 1,5 m / 6 m', 'Arco corto · +5 · 1d6+3 perforante · alcance 24 m / 96 m'], spells: [], details: [
      { title: 'Datos confirmados', entries: ['Pícara nivel 1 · mediana piesligeros · Criminal', 'FUE 8 (−1) · DES 16 (+3) · CON 12 (+1) · INT 13 (+1) · SAB 10 (+0) · CAR 16 (+3)', 'CA 14 · PG máximos 9 · velocidad 7,5 m · iniciativa +3', 'Ataque furtivo: +1d6 una vez por turno si se cumplen sus requisitos.'] },
      { title: 'Equipo y cantidades', entries: ['Arco corto y 20 flechas · 2 dagas · armadura de cuero', 'Herramientas de ladrón · mochila · bolsa con 1000 bolas de metal · 2 palanquetas · 2 frascos de aceite'] },
      { title: 'Trazabilidad', entries: ['Características transcritas de la ficha PDF de María facilitada por el usuario.'] }
    ] }, explorationBasics: ['jump'], combat: { armorClass: 14, speedMeters: 7.5, initiativeBonus: 3, ruleTraits: { sneakAttackDice: '1d6', brave: true }, attacks: [
      { id: 'dagger', label: 'Daga · +5 · 1d4+3 perforante · 1,5 m', attackBonus: 5, damageDice: '1d4', damageBonus: 3, damageType: 'perforante', range: { kind: 'melee', normalMeters: 1.5 }, finesse: true, animationType: 'melee' },
      { id: 'thrown-dagger', label: 'Lanzar daga · +5 · 1d4+3 perforante · 6 m', attackBonus: 5, damageDice: '1d4', damageBonus: 3, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 6 }, finesse: true, animationType: 'thrownWeapon' },
      { id: 'shortbow', label: 'Arco corto · +5 · 1d6+3 perforante · 24/96 m', attackBonus: 5, damageDice: '1d6', damageBonus: 3, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 24, longMeters: 96 }, animationType: 'arrow' }
    ] } },
    aoife: {
      maxHp: 8, initialHp: 7,
      combatResources: { 'spell-slot-1': { label: 'Espacios de conjuro nivel 1', current: 2, max: 2 } },
      explorationActions: [
        { id: 'mending', label: 'Remendar · 1 minuto', kind: 'cantrip', target: 'object', rangeMeters: 1.5, castingTime: '1 minuto', soundId: 'd8-night-sfx-magic-spark', guidance: 'El DM comprueba que la rotura sea compatible y narra la reparación al terminar el minuto de lanzamiento.' },
        { id: 'prestidigitation', label: 'Prestidigitación', kind: 'cantrip', target: 'point', rangeMeters: 3, soundId: 'd8-night-sfx-magic-spark', guidance: 'El DM aplica en la casilla elegida el pequeño efecto mágico acordado.' },
        { id: 'find-familiar', label: 'Encontrar familiar · ritual 1 h 10 min', kind: 'spell', target: 'point', rangeMeters: 3, castingTime: '1 h 10 min como ritual', ritual: true, soundId: 'd8-night-sfx-magic-ritual', guidance: 'El familiar aparece en un espacio desocupado elegido. El DM resuelve la forma, los componentes y el tiempo transcurrido.' },
        { id: 'floating-disk', label: 'Disco flotante · ritual 10 min', kind: 'spell', target: 'point', rangeMeters: 9, castingTime: '10 minutos como ritual', ritual: true, soundId: 'd8-night-sfx-magic-ritual', guidance: 'El disco aparece en un espacio desocupado visible. El DM valida el peso y su desplazamiento.' },
        { id: 'identify', label: 'Identificar · ritual 11 min', kind: 'spell', target: 'object', rangeMeters: 1.5, castingTime: '11 minutos como ritual', ritual: true, soundId: 'd8-night-sfx-magic-reveal', guidance: 'El DM revela la información mágica que corresponda al objeto tocado.' },
        { id: 'fog-cloud-exploration', label: 'Nube de niebla · concentración · espacio N1', kind: 'spell', target: 'point', rangeMeters: 36, concentration: true, resource: { id: 'spell-slot-1', cost: 1 }, soundId: 'd8-night-sfx-spell-arcane', guidance: 'El DM coloca una esfera de 6 m de radio muy oscurecida y registra la concentración hasta 1 hora.' }
      ],
      inventory: ['Arco corto de entrenamiento', '4 dagas', 'Bolsa de componentes', 'Libro de conjuros con musgo', 'Mochila', 'Conocimiento de magia popular', 'Tinta', 'Pluma', '10 hojas de pergamino', 'Bolsa de arena', 'Cuchillo pequeño', '2 antorchas', '23 po'],
      sheet: {
        level: 1, armorClass: 12, speedMeters: 7.5, strengthScore: 10, background: 'Hedgewitch',
        features: ['Maga: lanzamiento ritual, libro de conjuros y Recuperación arcana', 'Enana de las montañas: visión en la oscuridad 18 m, resistencia al veneno y entrenamiento enano', 'Recetas bien practicadas: con kit de herborista, la mitad de tiempo al fabricar pociones'],
        attacks: ['Golpe sin armas · +2 · 1 contundente · 1,5 m', 'Arco corto de entrenamiento · +2 · 1d6+2 perforante · 24/96 m', 'Daga (Destreza) · +4 · 1d4+2 perforante · 1,5 m / 6/18 m', 'Proyectil de fuego · +4 · 1d10 fuego · 36 m', 'Misil mágico · 3 dardos · 1d4+1 fuerza cada uno · 36 m · impacto automático'],
        spells: ['Trucos: Remendar, Prestidigitación, Proyectil de fuego', 'Nivel 1: Encontrar familiar, Disco flotante, Nube de niebla, Identificar, Caída de pluma, Misil mágico', 'Característica de conjuro: Inteligencia · ataque de conjuro +4 · CD de salvación 12'],
        details: [
          { title: 'Identidad', entries: ['Silverfarben Hotel · maga nivel 1 · enana de las montañas · Hedgewitch', 'Neutral buena · ella/elle · 18 años · ojos oscuros · pelo negro', '1,37 m · 56 kg · fe: los Dioses Pequeños'] },
          { title: 'Características', entries: ['FUE 10 (+0) · DES 14 (+2) · CON 14 (+2)', 'INT 15 (+2) · SAB 14 (+2) · CAR 8 (−1)', 'Bonificador de competencia +2 · iniciativa +2 · dados de golpe 1d6', 'Salvaciones: FUE +0 · DES +2 · CON +2 · INT +4 · SAB +4 · CAR −1'] },
          { title: 'Habilidades y competencias', entries: ['Competente: Trato con animales +4 · Arcanos +4 · Investigación +4 · Supervivencia +4', 'Armaduras ligeras y medias; hacha de batalla, hacha de mano, martillo ligero, martillo de guerra, daga, dardo, honda, bastón y ballesta ligera', 'Herramientas: suministros de cervecero, utensilios de cocina y kit de herborista · Idiomas: común y enano'] },
          { title: 'Trasfondo', entries: ['Círculo del Corazón Salvaje: grupo secreto de magia natural que protege el equilibrio.', 'Vínculo: una criatura llegó herida; tras curarla, se quedó a su lado.', 'Ideal: Libertad. Defecto: la prudencia la irrita y puede actuar con temeridad por conocimiento o poder.', 'Enemigo: Mortis Grimwither, un lich de las Marismas Oscuras.'] },
          { title: 'Uso en combate · 2024', entries: ['Golpe sin armas: +2 para impactar y 1 de daño contundente. El arco de entrenamiento no añade competencia: +2 para impactar.', 'Proyectil de fuego: acción mágica; ataque de conjuro +4, 1d10 de fuego y 36 m. Un objeto inflamable no llevado puede prenderse.', 'Misil mágico: acción mágica y un espacio de nivel 1; tres dardos impactan automáticamente y cada uno causa 1d4+1 de fuerza. La consola permite elegir el mismo objetivo o repartir los dardos.', 'Nube de niebla: acción mágica, concentración hasta 1 hora; esfera de 6 m de radio muy oscurecida a 36 m. El DM coloca y mantiene el área.', 'Caída de pluma: reacción cuando hasta cinco criaturas visibles caen a 18 m; ralentiza su caída durante 1 minuto.'] }
        ]
      },
      explorationBasics: ['jump'],
      combat: { armorClass: 12, speedMeters: 7.5, initiativeBonus: 2, spellAttackBonus: 4, spellSaveDc: 12, ruleTraits: { poisonResilience: true, darkvisionMeters: 18 }, damageResistances: ['veneno'], attacks: [
        { id: 'aoife-unarmed', label: 'Golpe sin armas · +2 · 1 contundente · 1,5 m', attackBonus: 2, damageDice: '1d1', damageBonus: 0, damageType: 'contundente', range: { kind: 'melee', normalMeters: 1.5 }, animationType: 'melee' },
        { id: 'aoife-shortbow', label: 'Arco corto de entrenamiento · +2 · 1d6+2 perforante · 24/96 m', attackBonus: 2, damageDice: '1d6', damageBonus: 2, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 24, longMeters: 96 }, animationType: 'arrow' },
        { id: 'aoife-dagger', label: 'Daga · +4 · 1d4+2 perforante · 1,5 m', attackBonus: 4, damageDice: '1d4', damageBonus: 2, damageType: 'perforante', range: { kind: 'melee', normalMeters: 1.5 }, finesse: true, animationType: 'melee' },
        { id: 'aoife-thrown-dagger', label: 'Lanzar daga · +4 · 1d4+2 perforante · 6/18 m', attackBonus: 4, damageDice: '1d4', damageBonus: 2, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 6, longMeters: 18 }, finesse: true, animationType: 'thrownWeapon' },
        { id: 'fire-bolt', label: 'Proyectil de fuego · +4 · 1d10 fuego · 36 m', attackBonus: 4, damageDice: '1d10', damageBonus: 0, damageType: 'fuego', range: { kind: 'ranged', normalMeters: 36 }, animationType: 'fireProjectile', magical: true },
        { id: 'magic-missile', label: 'Misil mágico · 3 dardos · 1d4+1 cada uno · automático · 36 m · espacio N1', attackBonus: 0, damageDice: '1d4', damageBonus: 1, damageType: 'fuerza', range: { kind: 'ranged', normalMeters: 36 }, attackCount: 3, automaticHit: true, resolution: 'automatic-damage', resource: { id: 'spell-slot-1', cost: 1 }, animationType: 'magicalProjectile', magical: true, soundId: 'd8-night-sfx-magic-spark' },
        { id: 'fog-cloud', label: 'Nube de niebla · concentración 1 h · esfera 6 m · 36 m · espacio N1', attackBonus: 0, damageDice: '1d1', damageBonus: 0, range: { kind: 'ranged', normalMeters: 36 }, resolution: 'guided', targeting: 'point', concentration: true, resource: { id: 'spell-slot-1', cost: 1 }, guidance: 'Esfera de 6 m de radio muy oscurecida, concentración hasta 1 hora. El DM coloca el área y registra la concentración.', magical: true },
        { id: 'feather-fall', label: 'Caída de pluma · reacción al caer · hasta 5 criaturas · 18 m · espacio N1', attackBonus: 0, damageDice: '1d1', damageBonus: 0, range: { kind: 'ranged', normalMeters: 18 }, resolution: 'guided', actionCost: 'reaction', resource: { id: 'spell-slot-1', cost: 1 }, soundId: 'd8-night-sfx-magic-ward', guidance: 'Reacción solo cuando una criatura visible cae. Elige hasta cinco criaturas: su descenso se ralentiza durante 1 minuto.', magical: true },
        { id: 'light-torch', label: 'Encender antorcha · Utilizar · consume 1 · luz 1 h', attackBonus: 0, damageDice: '1d1', damageBonus: 0, range: { kind: 'ranged', normalMeters: 1.5 }, resolution: 'guided', targeting: 'point', soundId: 'd8-night-sfx-magic-spark', guidance: 'Consume una antorcha de la mochila. Emite luz brillante a 6 m y tenue otros 6 m durante 1 hora; el DM registra cuándo se apaga.' }
      ] }
    }
  },
  encounter: { sceneId: 'mirror', mirrorPlayer: true, creature: { id: 'reflection', label: 'Reflejo de hielo', tokenId: 'reflection',
    color: '#7fc8e8', cell: mirrorNearbyCells[0] ?? mirrorCell, sheet: { maxHp: 7, armorClass: 14, speedMeters: 7.5, traits: ['Réplica helada: adopta las estadísticas y ataques de quien afronta el espejo, con el 75 % de sus PG.'], actions: ['Imita exactamente la acción de quien afronta el espejo; el DM resuelve los dados físicos.'], combat: { armorClass: 14, speedMeters: 7.5, initiativeBonus: 0, attacks: [] } } },
    note: 'Este encuentro solo aparece aquí. El reflejo se forma como una réplica helada de María, actúa después de ella e imita sus acciones; sus PG son el 75 %.' },
  mirrorInteraction: { sceneId: 'mirror', targetId: 'true-love-mirror', cells: mirrorNearbyCells, nearbyLabel: 'Mirar en el espejo', notice: 'El espejo se empaña de escarcha y tu reflejo cobra vida.', effectFrames: ['/art/tokens/Espejo/espejo_amor_verdadero_activacion_01.png', '/art/tokens/Espejo/espejo_amor_verdadero_activacion_02.png', '/art/tokens/Espejo/espejo_transformacion_01.png', '/art/tokens/Espejo/espejo_transformacion_02.png', '/art/tokens/Espejo/espejo_transformacion_03.png', '/art/tokens/Espejo/espejo_fx_copia_final.png'], durationMs: 1_600 },
  stageActorInteractions: [
    { sceneId: 'temple', targetId: 'anteros-temple', cells: d8AdjacentWalkableCells('temple', templeAnterosCell), nearbyLabel: 'Hablar con Anteros', responseAnimation: 'talk', notice: 'Anteros te escucha y responde. El DM guía la conversación y las decisiones del pacto.', durationMs: 2_200 },
    { sceneId: 'dinner', targetId: 'anteros-dinner', cells: d8AdjacentWalkableCells('dinner', dinnerAnterosCell), nearbyLabel: 'Brindar con Anteros', responseAnimation: 'react', notice: 'Anteros alza la mirada y responde al gesto. El DM decide el tono del desenlace.', durationMs: 1_800 }
  ],
  combatProfiles: {
    'anteros-temple': { maxHp: 71, armorClass: 16, speedMeters: 9, initiativeBonus: 4, identityId: 'anteros', traits: ['Percepción +6 y sentidos agudos: ventaja en Sabiduría (Percepción).', 'Vuelo 18 m: el DM registra desplazamiento aéreo por la cuadrícula; no se simula altura 3D.', 'Resistencia mágica: ventaja en salvaciones contra conjuros y efectos mágicos.', 'Inmunidad a la condición envenenada.'], ruleTraits: { magicResistance: true, flightMeters: 18 }, conditionImmunities: ['envenenada'], attacks: [{ id: 'longsword', label: 'Multiataque: espada larga ×2 · +5 · 1d8+2 cortante · 1,5 m', attackBonus: 5, damageDice: '1d8', damageBonus: 2, damageType: 'cortante', range: { kind: 'melee', normalMeters: 1.5 }, attackCount: 2, animationType: 'melee' }, { id: 'longbow', label: 'Multiataque: arco largo ×2 · +7 · 1d8+4 perforante · 45/180 m', attackBonus: 7, damageDice: '1d8', damageBonus: 4, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 45, longMeters: 180 }, attackCount: 2, animationType: 'arrow' }, { id: 'radiant-arrows', label: 'Flechas radiantes ×6 al mismo blanco · +7 · 2d8+4 radiante · 36 m · recarga 6', attackBonus: 7, damageDice: '2d8', damageBonus: 4, damageType: 'radiante', range: { kind: 'ranged', normalMeters: 36 }, attackCount: 6, lockSequenceTarget: true, recharge: { minimum: 6, maximum: 6 }, animationType: 'radiantArrow', magical: true }] },
    'anteros-dinner': { maxHp: 71, armorClass: 16, speedMeters: 9, initiativeBonus: 4, identityId: 'anteros', traits: ['Percepción +6 y sentidos agudos: ventaja en Sabiduría (Percepción).', 'Vuelo 18 m: el DM registra desplazamiento aéreo por la cuadrícula; no se simula altura 3D.', 'Resistencia mágica: ventaja en salvaciones contra conjuros y efectos mágicos.', 'Inmunidad a la condición envenenada.'], ruleTraits: { magicResistance: true, flightMeters: 18 }, conditionImmunities: ['envenenada'], attacks: [{ id: 'longsword', label: 'Multiataque: espada larga ×2 · +5 · 1d8+2 cortante · 1,5 m', attackBonus: 5, damageDice: '1d8', damageBonus: 2, damageType: 'cortante', range: { kind: 'melee', normalMeters: 1.5 }, attackCount: 2, animationType: 'melee' }, { id: 'longbow', label: 'Multiataque: arco largo ×2 · +7 · 1d8+4 perforante · 45/180 m', attackBonus: 7, damageDice: '1d8', damageBonus: 4, damageType: 'perforante', range: { kind: 'ranged', normalMeters: 45, longMeters: 180 }, attackCount: 2, animationType: 'arrow' }, { id: 'radiant-arrows', label: 'Flechas radiantes ×6 al mismo blanco · +7 · 2d8+4 radiante · 36 m · recarga 6', attackBonus: 7, damageDice: '2d8', damageBonus: 4, damageType: 'radiante', range: { kind: 'ranged', normalMeters: 36 }, attackCount: 6, lockSequenceTarget: true, recharge: { minimum: 6, maximum: 6 }, animationType: 'radiantArrow', magical: true }] },
    'rose-garden-1': { maxHp: 22, armorClass: 11, speedMeters: 6, initiativeBonus: 1, startsVisible: false, traits: ['Apariencia falsa: mientras no se mueve es indistinguible de un rosal normal.', 'Espinas: tocar físicamente el rosal causa 1 de daño perforante; atacar a distancia o con un arma no activa este rasgo.'], conditionImmunities: ['envenenada'], attacks: [{ id: 'thorn-bite', label: 'Multiataque: espina ×2 · +3 · 1 perforante · 1,5 m', attackBonus: 3, damageDice: '1d1', damageBonus: 0, damageType: 'perforante', range: { kind: 'melee', normalMeters: 1.5 }, attackCount: 2, animationType: 'melee' }, { id: 'entangle', label: 'Enredar · TS DES CD 11 · restringida · escapar CD 11 · 6 m · recarga 5–6', attackBonus: 0, damageDice: '1d1', damageBonus: 0, range: { kind: 'ranged', normalMeters: 6 }, save: { ability: 'dex', dc: 11, failureCondition: 'restringida', escapeDc: 11, endsWhenSourceDefeated: true }, recharge: { minimum: 5, maximum: 6 }, animationType: 'vine' }] },
    'rose-garden-2': { maxHp: 22, armorClass: 11, speedMeters: 6, initiativeBonus: 1, startsVisible: false, traits: ['Apariencia falsa: mientras no se mueve es indistinguible de un rosal normal.', 'Espinas: tocar físicamente el rosal causa 1 de daño perforante; atacar a distancia o con un arma no activa este rasgo.'], conditionImmunities: ['envenenada'], attacks: [{ id: 'thorn-bite', label: 'Multiataque: espina ×2 · +3 · 1 perforante · 1,5 m', attackBonus: 3, damageDice: '1d1', damageBonus: 0, damageType: 'perforante', range: { kind: 'melee', normalMeters: 1.5 }, attackCount: 2, animationType: 'melee' }, { id: 'entangle', label: 'Enredar · TS DES CD 11 · restringida · escapar CD 11 · 6 m · recarga 5–6', attackBonus: 0, damageDice: '1d1', damageBonus: 0, range: { kind: 'ranged', normalMeters: 6 }, save: { ability: 'dex', dc: 11, failureCondition: 'restringida', escapeDc: 11, endsWhenSourceDefeated: true }, recharge: { minimum: 5, maximum: 6 }, animationType: 'vine' }] },
    'fritz-garden': villagerProfile('fritz'),
    'bartender-cafe': villagerProfile('bartender'),
    'patron-cafe': villagerProfile('patron'),
    'woman-cafe': villagerProfile('woman-cafe'),
    'ben-market': villagerProfile('ben'),
    'margaret-market': villagerProfile('margaret'),
    'boris-market': villagerProfile('boris')
  }
};
